version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn install -DiskTests
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/flowmax.jar
  discard-paths: yes